### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Muvkina** [eudaldgr/kiss-garbage#1]
I think due to the simplicity of kiss build files you should consider a permissive license. This is obviously your choice at the end of the day. However even the [FSF](https://www.gnu.org/licenses/license-recommendations.html) believes that permissive licenses should be used on small works. It would make it a lot easier for others to use these builds in their own repos :)

**Comment by eudaldgr** [comment]
I don't understand the point, what's your purpose with the copy of my builds you can't do with this license? You want to create a derivative work and sell with other license? Or is it simply a diference in form?
Because I think you can use my builds in your repository under this license, preserving it of course

**Comment by Muvkina** [comment]
I personally would like to have my repository under the mit license like most repos but due to the gpl I cannot. However it is not that big of an issue if you arent comfortable I will just remove your builds since I have not looked at them and write them myself.

**Comment by eudaldgr** [comment]
I'm sorry i can't help. Like you i want my repository with my own chosen license.

**Comment by Muvkina** [comment]
That is fair enough like I said was just wondering

**Comment by eudaldgr** [comment]
Well, i close this then.
